import {records,LIMIT,datesFor,aggregate,statusFor} from './mock-data.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let range=localStorage.range||'7', metric='total', page=1, sort='date', asc=false;
const fmt=n=>new Intl.NumberFormat('en-US',{notation:n>99999?'compact':'standard',maximumFractionDigits:1}).format(n);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const day=d=>d.toISOString().slice(0,10); const rangeName=r=>({today:'Today','3':'Last 3 days','7':'Last 7 days','30':'Last 30 days',month:'This month',previous:'Previous month',custom:'Custom range'})[r];
function selected(){const {start,end}=datesFor(range,{from:$('#from').value,to:$('#to').value});return records.filter(r=>r.date>=start&&r.date<=end)}
function previous(){const {start,end}=datesFor(range,{from:$('#from').value,to:$('#to').value});const days=Math.max(1,Math.ceil((end-start)/86400000)+1);const priorEnd=new Date(start);priorEnd.setMilliseconds(-1);const priorStart=new Date(priorEnd);priorStart.setDate(priorStart.getDate()-days+1);return records.filter(r=>r.date>=priorStart&&r.date<=priorEnd)}
function change(current,prior,key){if(!prior[key])return 'No previous data';const n=Math.round((current[key]-prior[key])/prior[key]*100);return `<span class="${n>0?'warning':'good'}">${n>0?'↑':'↓'} ${Math.abs(n)}%</span> vs previous period`}
function renderSummary(items){const a=aggregate(items),p=aggregate(previous()),pct=Math.min(100,a.total/LIMIT*100),stat=statusFor(pct);$('#summary').innerHTML=`
<article class="card ring-card"><div class="ring" style="--pct:${pct}"><span>${pct.toFixed(1)}%</span></div><div><p class="eyebrow">TOKEN ALLOWANCE</p><div class="value">${fmt(a.total)} <small>/ ${fmt(LIMIT)}</small></div><div class="hint ${stat}">${(100-pct).toFixed(1)}% remaining · Demo reset: tomorrow, 6:00 PM</div></div></article>
${card('TOTAL TOKENS',fmt(a.total),change(a,p,'total'))}${card('INPUT TOKENS',fmt(a.input),change(a,p,'input'))}${card('OUTPUT TOKENS',fmt(a.output),change(a,p,'output'))}${card('EST. COST',money(a.cost),change(a,p,'cost'))}${card('REQUESTS',fmt(a.requests),change(a,p,'requests'))}`}
function card(title,value,hint){return `<article class="card"><p class="eyebrow">${title}</p><div class="value">${value}</div><div class="hint">${hint}</div></article>`}
function renderChart(items){const buckets={};items.forEach(x=>{const k=day(x.date);(buckets[k]??=[]).push(x)});const points=Object.entries(buckets).map(([date,v])=>({date,a:aggregate(v)})).sort((a,b)=>a.date.localeCompare(b.date));const max=Math.max(...points.map(x=>x.a[metric]),1);$('#chart').innerHTML=points.length?points.map(x=>`<div class="bar" style="height:${Math.max(4,x.a[metric]/max*100)}%" data-label="${x.date}: ${metric==='cost'?money(x.a[metric]):fmt(x.a[metric])}"></div>`).join(''):`<p class="hint">No demo records in this date range.</p>`}
function renderModels(items){const groups={};items.forEach(x=>(groups[x.model]??=[]).push(x));const all=aggregate(items);const vals=Object.entries(groups).map(([name,v])=>({name,a:aggregate(v)})).sort((a,b)=>b.a.total-a.a.total);const colors=['#8c9aff','#4dd69a','#f7bd4d','#ff7186'];let cursor=0;const segments=vals.map((x,i)=>{const part=all.total?x.a.total/all.total*100:0;const s=`${colors[i]} ${cursor}% ${cursor+part}%`;cursor+=part;return s});$('#donut').innerHTML=`<div class="donut" style="background:conic-gradient(${segments.join(',')})"><div>${fmt(all.total)}<small>tokens</small></div></div><div class="legend">${vals.map((x,i)=>`<span><b><i class="dot" style="background:${colors[i]}"></i>${x.name}</b> ${all.total?(x.a.total/all.total*100).toFixed(0):0}%</span>`).join('')}</div>`;$('#modelRows').innerHTML=vals.map(x=>`<tr><td class="model-name">${x.name}</td><td>${fmt(x.a.requests)}</td><td>${fmt(x.a.input)}</td><td>${fmt(x.a.output)}</td><td>${fmt(x.a.total)}</td><td>${money(x.a.cost)}</td><td class="share">${all.total?(x.a.total/all.total*100).toFixed(1):0}%</td></tr>`).join('');const peak=items.reduce((m,x)=>!m||x.total>m.total?x:m,null);$('#insight').innerHTML=peak?`<b>Peak usage</b><br>${peak.date.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})} at ${peak.date.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})} · ${fmt(peak.total)} tokens`:'No peak to show.'}
function renderActivity(items){const q=$('#search').value.toLowerCase();let v=items.filter(x=>`${x.model} ${x.status}`.toLowerCase().includes(q)).sort((a,b)=>asc?a[sort]-b[sort]:b[sort]-a[sort]);if(sort==='date')v.sort((a,b)=>asc?a.date-b.date:b.date-a.date);const pages=Math.max(1,Math.ceil(v.length/8));page=Math.min(page,pages);$('#activityRows').innerHTML=v.slice((page-1)*8,page*8).map(x=>`<tr><td>${x.date.toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</td><td>${x.model}</td><td>${fmt(x.input)}</td><td>${fmt(x.output)}</td><td>${fmt(x.total)}</td><td>${money(x.cost)}</td><td>${x.status}</td></tr>`).join('')||'<tr><td colspan="7">No sample records match this selection.</td></tr>';$('#pageInfo').textContent=`Page ${page} of ${pages}`;$('#prev').disabled=page===1;$('#next').disabled=page===pages}
function render(){const items=selected();$('#subtitle').textContent=`${rangeName(range)} · Last updated: just now · Demo data`;renderSummary(items);renderChart(items);renderModels(items);renderActivity(items);$$('#rangeControls button').forEach(b=>b.classList.toggle('active',b.dataset.range===range))}
$('#rangeControls').addEventListener('click',e=>{if(!e.target.dataset.range)return;range=e.target.dataset.range;localStorage.range=range;page=1;render()});$('#from').addEventListener('change',()=>{if($('#from').value&&$('#to').value){range='custom';localStorage.range=range;render()}});$('#to').addEventListener('change',()=>{if($('#from').value&&$('#to').value){range='custom';localStorage.range=range;render()}});$('#metricTabs').addEventListener('click',e=>{if(!e.target.dataset.metric)return;metric=e.target.dataset.metric;$$('#metricTabs button').forEach(b=>b.classList.toggle('active',b===e.target));renderChart(selected())});$('#search').addEventListener('input',()=>{page=1;renderActivity(selected())});$$('[data-sort]').forEach(b=>b.addEventListener('click',()=>{const n=b.dataset.sort;asc=n===sort?!asc:false;sort=n;renderActivity(selected())}));$('#prev').onclick=()=>{page--;renderActivity(selected())};$('#next').onclick=()=>{page++;renderActivity(selected())};$('#themeButton').onclick=()=>{document.body.classList.toggle('light');localStorage.theme=document.body.classList.contains('light')?'light':'dark'};$('#resetDemo').onclick=()=>{localStorage.removeItem('range');localStorage.removeItem('theme');range='7';page=1;document.body.classList.remove('light');$('#from').value='';$('#to').value='';$('#notice').textContent='Demo preferences reset.';$('#notice').classList.remove('hidden');render()};if(localStorage.theme==='light')document.body.classList.add('light');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
